### ISSUE TITLE
Imported procedure name - temp workaround

### ISSUE THREAD

**Issue by adesutherland** [adesutherland/CREXX#134]
### Discussed in https://github.com/adesutherland/CREXX/discussions/133

Temporally import procedures as "func.func" rather than "global.func"

**Comment by rvjansen** [comment]
Thanks. But it still does not generate the called functions in their own func.func form. If it does, I can call the rexx bifs and the rxas bifs with one rexx test driver, without editing the generated rxas.

**Comment by rvjansen** [comment]
sorry about that! I thought it was in the last drop - switched laptops because of batteries - and this one probably was a few commits behind. Yes, this works great! I can now work with Peter on the bif library and mix and match rexx and rxas implementations. Merged the changes into f0035.

Btw I renamed 'lib/rxfns/zero' to 'libb/rxfns/rexx' as it was nice for a few moments but it kept confusing me.
It works like a charm now.

**Comment by rvjansen** [comment]
Like I said, works like a charm.
