### ISSUE TITLE
function prototype maybe used incorrectly

### ISSUE THREAD

**Issue by Peter-Jacob** [adesutherland/CREXX#148]
As with the countstr/pos call arisen: you can use an invalid prototype statement not matching the called function requirements.  
1. the prototype statement of a function must be defined at the caller level and can contain invalid parms
2. the callee has a fixed requirement of the parms
3. in fact the prototype statement should be a property of the callee and predefined at its level
4. at the callee level we don't have a prototype definition, it's just coded as if there was one.
5. if we had one (4.) caller could import the prototype from the callee

as 3, 4. and 5. can't be easily accomplished. The only way I see to use prototypes with extreme care
Maybe we can set up a rexx that supports an automatic import in the future, although I am not sure if it's worth it.

**Comment by rvjansen** [comment]
We can very easily use the #include trick that I use in my makefiles, it would solve this problem. But even this has two modes nowadays, where gcc does more than just include - it also runs the tokenizer - and we don’t want to be dependent on that.
I think that for functions that are part of some standard, we should have one ‘good’ copy somewhere that can be quickly reverse engineered by the compiler in order to generate the right signature. It can be reflections based so it will also work on other signatures for functions/methods that people think up.

**Comment by rvjansen** [comment]
this might be part of the rxln/rxar work; to find a place to store the known, standardised signatures. But I think that in the end this is a programmer responsibility, we might think about warnings. The problem is limited to level B; 'ordinary' Classic Rexx programmers don't need to worry about this.
