### ISSUE TITLE
  what to use as string length: string_length or string_chars?

### ISSUE THREAD

**Issue by Peter-Jacob** [adesutherland/CREXX#210]
which string length is the correct one: string_length or string_chars?
The STRLEN instruction uses v->string_chars for UTF8 and v->string_length for ASCII. 
Some other instructions use just v->string_length also for UTF8 (e.g. STOI_REG , SCONCAT_REG_STRING_REG, and many more)

For my SUBSTRING function, I must know on which I can rely.

**Comment by adesutherland** [comment]
It is not that elegant but the answer is

- v->string_length is the number of **bytes** that the string takes up (remembering that chars can be multibyte)
- For UTF8 therefore v->string_chars is the number of actual characters in the string
- For NOT UTF8 (ASCII) v->string_chars is not used as it not needed because the number of characters = the number of bytes

**Hopefully** the instructions that just use v->string_length are doing this because they only care about the number of bytes ...

**Comment by Peter-Jacob** [comment]
Are in UTF8 both vars maintained (number bytes, number of chars )? Von meinem Huawei-Telefon gesendet-------- Ursprüngliche Nachricht --------Von: Adrian Sutherland ***@***.***>Datum: Sa., 13. Nov. 2021, 18:09An: adesutherland/CREXX ***@***.***>Cc: Peter-Jacob ***@***.***>, Author ***@***.***>Betreff: Re: [adesutherland/CREXX]   what to use as string length: string_length or string_chars? (Issue #210)
It is not that elegant but the answer is
v->string_length is the number of bytes that the string takes up (remembering that chars can be multibyte)For UTF8 therefore v->string_chars is the number of actual characters in the stringFor NOT UTF8 (ASCII) v->string_chars is not used as it not needed because the number of characters = the number of bytes
Hopefully the instructions that just use v->string_length are doing this because they only care about the number of bytes ...

**Comment by adesutherland** [comment]
> Are in UTF8 both vars maintained (number bytes, number of chars )? 

Yes (of course there may be some bugs!)

**Comment by Peter-Jacob** [comment]
thanks a lot!
