### ISSUE TITLE
unclear instructions

### ISSUE THREAD

**Issue by Peter-Jacob** [adesutherland/CREXX#26]
for me the purpose of the following instructions are not clear: 
    STR2INT_REG_xxx_xxx  String to Int op1 = op2[op3]    
      is op3 offset in a string to convert a single character, or 
      offset in a string to convert the remaining string part
MULTF_REG_REG_FLOAT  Convert and Multiply to Float (op1=op2*op3)  and all instructions of this type: ADDF, SUBF, DIVF
    which type can op2 have? 
        string, integer, or just string?

**Comment by adesutherland** [comment]
1. It is "op3 offset in a string to convert a single character"
2. Convert means that the second register should be converted to a float (e.g. from a string)

Sorry for being unclear!!

**Comment by Peter-Jacob** [comment]
MULTF_REG_REG_FLOAT Convert and Multiply to Float (op1=op2*op3) and all instructions of this type: ADDF, SUBF, DIVF

sorry, if I insist on more information, it's still not clear to me. The basic instruction is to return a float of an arithmetic operation (in this case multiply). So the second operand in this example could be integer or string (can't be a float as FMULT would have been chosen). The instruction sequence is: 
for a string:
     float result = convert2Float(string)*float(r3)  
for an integer
   float result = integer of r2 * float(r3)    conversion will be implicitly done by the compiler. 

Am I correct on these assumptions?

**Comment by adesutherland** [comment]
Hi Peter - Yes you are correct. 

The only point is that "can't be a float as FMULT would have been chosen" is not right. The REXX compiler might not know if the register is a float or an integer or a string - and so use this instruction.

Also int is a long long and float is a double - I am not sure if the C compiler will not convert to int implicitly rather than long long?

Finally - we need to discuss a way of determining new instructions - remember what I put down was just a braindump! One area to look at is the ANSI REXX low level functions discussed in the ANSI standard.
